### ISSUE TITLE
VFX: Checkpoints

### ISSUE THREAD

**Issue by Tmac4930** [luke-goldfain/Hangtime-Prototype#16]

**Comment by luke-goldfain** [comment]
I will work on using shaders to make the surface of the checkpoint unique. I expect that @Tmac4930 will work on the light-pillar and glowing effect like he planned.

**Comment by Tmac4930** [comment]
Ran into some problems with shader graph and the LWRP but I should be able to get caught up on this over the weekend.

**Comment by Tmac4930** [comment]
Eric did my part on this issue, so I think it's ready to close.
