### ISSUE TITLE
Hawk Model

### ISSUE THREAD

**Issue by Tmac4930** [luke-goldfain/Hangtime-Prototype#18]

**Comment by bigorangestar** [comment]
![HawkManBaseWIP_01](https://user-images.githubusercontent.com/32888318/65299504-6e318700-db35-11e9-85c5-ac68108e8819.JPG)
![HawkManBaseWIP_02](https://user-images.githubusercontent.com/32888318/65299505-6e318700-db35-11e9-9bfd-45e591f28ca2.JPG)

Still a work in progress, should definitely be done (and at the very least, unwrapped) by next week.

**Comment by bigorangestar** [comment]
![HawkmanBaseMeshBack](https://user-images.githubusercontent.com/32888318/65351009-a2945a00-dbac-11e9-8500-79724b44518f.PNG)
![HawkmanBaseMeshFront](https://user-images.githubusercontent.com/32888318/65351011-a2945a00-dbac-11e9-8950-38395c58309f.PNG)

All done!  Time to unwrap, do a hi-res, all that good stuff....
