### ISSUE TITLE
Clean Up Terrain & Environments

### ISSUE THREAD

**Issue by Tmac4930** [luke-goldfain/Hangtime-Prototype#9]

**Comment by bigorangestar** [comment]
I didn't know I was going to be responsible for this one!  But that's fine, I don't mind doing it once there's environments posted to clean up.

**Comment by Tmac4930** [comment]
Sorry, Sunnie, this wasn't your issue, I just mistook you for Kyler, I've never worked with any of you artist in GitHub before and Alex is the only one who made himself easy to identify,

**Comment by Tmac4930** [comment]
We have added in a new terrain more focused on the games core movement mechanics and a modular kit is being made in conjunction to allow placement of additional pieces.
